# Generated by Django 4.2.11 on 2024-04-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_share_available_remove_share_share_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
