# Generated by Django 3.2.8 on 2021-10-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minifacebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
